/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Staff;

import Admin.display_items;
import accounts.Login;
import accounts.UserManager;
import com.formdev.flatlaf.FlatLightLaf;
import config.actionLogs;
import config.databaseConnector;
import config.display_time;
import config.flatlaftTable;
import config.search;
import config.sorter;
import java.awt.geom.RoundRectangle2D;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JToggleButton;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.TableModel;
import raven.toast.Notifications;

/**
 *
 * @author rico
 */
public class staff_dashboard extends javax.swing.JFrame {

    /**
     * Creates new form user_dashboard
     */
    int user_id = UserManager.getLoggedInUserId();

    public staff_dashboard() {
        initComponents();
        display_time.now(date_today);
        display_items.to_staff_table(staff_table);
        dashboard_btn.setSelected(true);
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 30, 30));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        top_navbar = new javax.swing.JPanel();
        dashboard_btn = new javax.swing.JToggleButton();
        logout_btn = new javax.swing.JToggleButton();
        date_today = new javax.swing.JLabel();
        profile_icon1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tabs = new javax.swing.JTabbedPane();
        dashboard = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        total_items = new javax.swing.JLabel();
        search_btn_manage = new javax.swing.JTextField();
        find_btn_manage = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        discontinued = new javax.swing.JLabel();
        archived = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        new_btn = new javax.swing.JToggleButton();
        jLabel23 = new javax.swing.JLabel();
        prelove_btn = new javax.swing.JToggleButton();
        filterContainer2 = new javax.swing.JPanel();
        supplier = new javax.swing.JComboBox<>();
        filterContainer3 = new javax.swing.JPanel();
        size_option = new javax.swing.JComboBox<>();
        filterContainer4 = new javax.swing.JPanel();
        color_option = new javax.swing.JComboBox<>();
        filterContainer5 = new javax.swing.JPanel();
        category = new javax.swing.JComboBox<>();
        filterContainer6 = new javax.swing.JPanel();
        material = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        decrement = new javax.swing.JButton();
        increment = new javax.swing.JButton();
        buy_now_btn = new javax.swing.JButton();
        reset_btn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        display_quantity = new javax.swing.JTextField();
        manage_table_container = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        staff_table = new javax.swing.JTable();
        call_admin_btn = new javax.swing.JButton();
        confimation = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        top_navbar.setBackground(new java.awt.Color(204, 204, 0));
        top_navbar.setOpaque(false);
        top_navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboard_btn.setBackground(new java.awt.Color(255, 229, 246));
        dashboard_btn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        dashboard_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-dashboard.png"))); // NOI18N
        dashboard_btn.setText(" Dashboard");
        dashboard_btn.setBorder(null);
        dashboard_btn.setBorderPainted(false);
        dashboard_btn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-dashboard-selected.png"))); // NOI18N
        dashboard_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboard_btnActionPerformed(evt);
            }
        });
        top_navbar.add(dashboard_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 120, 30));
        UXmethods.RoundBorders.setArcStyle(dashboard_btn, 30);

        logout_btn.setBackground(new java.awt.Color(255, 229, 246));
        logout_btn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        logout_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-logout.png"))); // NOI18N
        logout_btn.setText(" Logout");
        logout_btn.setBorder(null);
        logout_btn.setBorderPainted(false);
        logout_btn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-logout-selected.png"))); // NOI18N
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });
        top_navbar.add(logout_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 100, 30));
        UXmethods.RoundBorders.setArcStyle(logout_btn, 30);

        date_today.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        date_today.setForeground(new java.awt.Color(51, 51, 51));
        date_today.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        date_today.setText("Date");
        top_navbar.add(date_today, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 20, 250, 30));

        profile_icon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profile_icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-profile.png"))); // NOI18N
        top_navbar.add(profile_icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 20, 60, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        top_navbar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 60));

        jPanel1.add(top_navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1380, 70));

        tabs.setTabPlacement(javax.swing.JTabbedPane.RIGHT);

        dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabel5.setText("Items");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 70, 40));

        jPanel4.setBackground(new java.awt.Color(255, 229, 246));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("total items");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 80, 40));

        total_items.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        total_items.setText("1");
        jPanel4.add(total_items, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 40));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 140, 40));
        UXmethods.RoundBorders.setArcStyle(jPanel4, 30);

        search_btn_manage.setSelectionColor(new java.awt.Color(255, 229, 246));
        search_btn_manage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_btn_manageKeyReleased(evt);
            }
        });
        jPanel3.add(search_btn_manage, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 300, 40));
        flatlaftTable.searchBar(search_btn_manage);
        UXmethods.RoundBorders.setArcStyle(search_btn_manage, 30);

        find_btn_manage.setBackground(new java.awt.Color(255, 229, 246));
        find_btn_manage.setText("Find");
        find_btn_manage.setBorder(null);
        find_btn_manage.setBorderPainted(false);
        find_btn_manage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                find_btn_manageActionPerformed(evt);
            }
        });
        jPanel3.add(find_btn_manage, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 60, 40));
        UXmethods.RoundBorders.setArcStyle(find_btn_manage, 30);

        jPanel8.setBackground(new java.awt.Color(249, 249, 249));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("SIZE OPTIONS");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 310, 50));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("COLOR OPTIONS");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 310, 50));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("CATEGORY");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 310, 50));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("SUPPLIER");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 310, 50));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("CLOTH CONDITION");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, 50));

        discontinued.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        discontinued.setForeground(new java.awt.Color(102, 102, 102));
        discontinued.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel8.add(discontinued, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 50, 40));

        archived.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        archived.setForeground(new java.awt.Color(102, 102, 102));
        archived.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel8.add(archived, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 60, 40));

        jLabel33.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel33.setText("New");
        jPanel8.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 50, 40));

        new_btn.setBackground(new java.awt.Color(255, 229, 246));
        new_btn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        new_btn.setBorder(null);
        new_btn.setBorderPainted(false);
        new_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_btnActionPerformed(evt);
            }
        });
        jPanel8.add(new_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 150, 40));
        UXmethods.RoundBorders.setArcStyle(new_btn, 30);

        jLabel23.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel23.setText("Pre-love");
        jPanel8.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 60, 40));

        prelove_btn.setBackground(new java.awt.Color(255, 229, 246));
        prelove_btn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        prelove_btn.setBorder(null);
        prelove_btn.setBorderPainted(false);
        prelove_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prelove_btnActionPerformed(evt);
            }
        });
        jPanel8.add(prelove_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 150, 40));
        UXmethods.RoundBorders.setArcStyle(prelove_btn, 30);

        filterContainer2.setBackground(new java.awt.Color(255, 229, 246));
        filterContainer2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        supplier.setBackground(new java.awt.Color(255, 229, 246));
        supplier.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        supplier.setForeground(new java.awt.Color(51, 51, 51));
        supplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT SUPPLIER", "A", "B", "C", "D" }));
        supplier.setSelectedIndex(0);
        supplier.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierActionPerformed(evt);
            }
        });
        filterContainer2.add(supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 20));

        jPanel8.add(filterContainer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 310, 40));
        UXmethods.RoundBorders.setArcStyle(filterContainer2, 30);

        filterContainer3.setBackground(new java.awt.Color(255, 229, 246));
        filterContainer3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        size_option.setBackground(new java.awt.Color(255, 229, 246));
        size_option.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        size_option.setForeground(new java.awt.Color(51, 51, 51));
        size_option.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SIZE OPTIONS", "S", "M", "L", "XL", "XXL" }));
        size_option.setSelectedIndex(0);
        size_option.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        size_option.setOpaque(true);
        size_option.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                size_optionActionPerformed(evt);
            }
        });
        filterContainer3.add(size_option, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 20));

        jPanel8.add(filterContainer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 310, 40));
        UXmethods.RoundBorders.setArcStyle(filterContainer3, 30);

        filterContainer4.setBackground(new java.awt.Color(255, 229, 246));
        filterContainer4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        color_option.setBackground(new java.awt.Color(255, 229, 246));
        color_option.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        color_option.setForeground(new java.awt.Color(51, 51, 51));
        color_option.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT COLOR", "Blue", "Green", "Yellow", "Black", "Orange" }));
        color_option.setSelectedIndex(0);
        color_option.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        color_option.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color_optionActionPerformed(evt);
            }
        });
        filterContainer4.add(color_option, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, -1));

        jPanel8.add(filterContainer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 310, 40));
        UXmethods.RoundBorders.setArcStyle(filterContainer4, 30);

        filterContainer5.setBackground(new java.awt.Color(255, 229, 246));
        filterContainer5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        category.setBackground(new java.awt.Color(255, 229, 246));
        category.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        category.setForeground(new java.awt.Color(51, 51, 51));
        category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT CATEGORY", "Casual", "Formal", "Activewear" }));
        category.setSelectedIndex(0);
        category.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryActionPerformed(evt);
            }
        });
        filterContainer5.add(category, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 20));

        jPanel8.add(filterContainer5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 310, 40));
        UXmethods.RoundBorders.setArcStyle(filterContainer5, 30);

        filterContainer6.setBackground(new java.awt.Color(255, 229, 246));
        filterContainer6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        material.setBackground(new java.awt.Color(255, 229, 246));
        material.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        material.setForeground(new java.awt.Color(51, 51, 51));
        material.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT MATERIAL", "100% Cotton", "Polyester blend", "Leather" }));
        material.setSelectedIndex(0);
        material.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        material.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialActionPerformed(evt);
            }
        });
        filterContainer6.add(material, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 20));

        jPanel8.add(filterContainer6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 310, 40));
        UXmethods.RoundBorders.setArcStyle(filterContainer6, 30);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("MATERIAL");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 310, 50));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        decrement.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        decrement.setText("-");
        decrement.setBorderPainted(false);
        decrement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decrementActionPerformed(evt);
            }
        });
        jPanel5.add(decrement, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 40));
        UXmethods.RoundBorders.setArcStyle(decrement, 10);

        increment.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        increment.setText("+");
        increment.setBorderPainted(false);
        increment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incrementActionPerformed(evt);
            }
        });
        jPanel5.add(increment, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 40, 40));
        UXmethods.RoundBorders.setArcStyle(increment, 10);

        buy_now_btn.setBackground(new java.awt.Color(193, 232, 153));
        buy_now_btn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        buy_now_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-buy.png"))); // NOI18N
        buy_now_btn.setText(" Buy now");
        buy_now_btn.setBorderPainted(false);
        buy_now_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buy_now_btnActionPerformed(evt);
            }
        });
        jPanel5.add(buy_now_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 310, 40));
        UXmethods.RoundBorders.setArcStyle(buy_now_btn, 30);

        reset_btn.setBackground(new java.awt.Color(250, 233, 244));
        reset_btn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        reset_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-reset.png"))); // NOI18N
        reset_btn.setText(" Reset");
        reset_btn.setBorderPainted(false);
        reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_btnActionPerformed(evt);
            }
        });
        jPanel5.add(reset_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 90, 40));
        UXmethods.RoundBorders.setArcStyle(reset_btn, 30);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        display_quantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        display_quantity.setText("1");
        display_quantity.setAutoscrolls(false);
        display_quantity.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        display_quantity.setSelectionColor(new java.awt.Color(255, 229, 246));
        display_quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display_quantityActionPerformed(evt);
            }
        });
        jPanel6.add(display_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 20));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 70, 40));
        UXmethods.RoundBorders.setArcStyle(jPanel6, 10);

        jPanel8.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 350, 140));
        UXmethods.RoundBorders.setArcStyle(jPanel5, 20);

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 350, 790));
        UXmethods.RoundBorders.setArcStyle(jPanel8, 20);

        manage_table_container.setBackground(new java.awt.Color(249, 249, 249));
        manage_table_container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        staff_table.setAutoCreateRowSorter(true);
        staff_table.setBackground(new java.awt.Color(249, 249, 249));
        staff_table.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        staff_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        staff_table.setFocusable(false);
        staff_table.setGridColor(new java.awt.Color(0, 0, 0));
        staff_table.setSelectionBackground(new java.awt.Color(255, 229, 246));
        staff_table.getTableHeader().setResizingAllowed(false);
        staff_table.getTableHeader().setReorderingAllowed(false);
        staff_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staff_tableMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(staff_table);

        manage_table_container.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 970, 750));

        jPanel3.add(manage_table_container, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 970, 790));
        UXmethods.RoundBorders.setArcStyle(manage_table_container, 20);

        call_admin_btn.setBackground(new java.awt.Color(249, 249, 249));
        call_admin_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-support-admin.png"))); // NOI18N
        call_admin_btn.setBorderPainted(false);
        jPanel3.add(call_admin_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1319, 110, 40, 40));
        UXmethods.RoundBorders.setArcStyle(call_admin_btn, 50);

        dashboard.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 980));

        tabs.addTab("tab1", dashboard);

        confimation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        confimation.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));

        tabs.addTab("tab2", confimation);

        jPanel1.add(tabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 980));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 980));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void handleButtonSelection(int tabIndex, JToggleButton selectedButton, JToggleButton... otherButtons) {
        tabs.setSelectedIndex(tabIndex);

        selectedButton.setSelected(true);

        for (JToggleButton btn : otherButtons) {
            btn.setSelected(false);
        }
    }

    private void dashboard_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboard_btnActionPerformed
        tabs.setSelectedIndex(0);
    }//GEN-LAST:event_dashboard_btnActionPerformed

    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
        Login out = new Login();
        out.setVisible(true);
        this.dispose();

        String action = "Logged out";
        String details = "User " + user_id + " Successfully logged out!";
        actionLogs.recordAdminLogs(user_id, action, details);
    }//GEN-LAST:event_logout_btnActionPerformed

    private void search_btn_manageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_btn_manageKeyReleased
        search.searchResult(staff_table, search_btn_manage);
    }//GEN-LAST:event_search_btn_manageKeyReleased

    private void find_btn_manageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_find_btn_manageActionPerformed
        search.searchResult(staff_table, search_btn_manage);
    }//GEN-LAST:event_find_btn_manageActionPerformed

    private void new_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_btnActionPerformed
        new_btn.setSelected(true);
        prelove_btn.setSelected(false);
        cloth_type = "new";
        sorter.toggle(staff_table, cloth_type);
    }//GEN-LAST:event_new_btnActionPerformed

    String cloth_type;

    private void prelove_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prelove_btnActionPerformed
        new_btn.setSelected(false);
        prelove_btn.setSelected(true);
        cloth_type = "prelove";
        sorter.toggle(staff_table, cloth_type);
    }//GEN-LAST:event_prelove_btnActionPerformed

    private void supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierActionPerformed
        sorter.searchResult(staff_table, supplier);
    }//GEN-LAST:event_supplierActionPerformed

    private void size_optionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_size_optionActionPerformed
        sorter.searchResult(staff_table, size_option);
    }//GEN-LAST:event_size_optionActionPerformed

    private void color_optionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color_optionActionPerformed
        sorter.searchResult(staff_table, color_option);
    }//GEN-LAST:event_color_optionActionPerformed

    private void categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryActionPerformed
        sorter.searchResult(staff_table, category);
    }//GEN-LAST:event_categoryActionPerformed

    private void reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_btnActionPerformed
        new_btn.setSelected(false);
        prelove_btn.setSelected(false);
        size_option.setSelectedIndex(0);
        color_option.setSelectedIndex(0);
        category.setSelectedIndex(0);
        supplier.setSelectedIndex(0);
        display_quantity.setText("0");
        display_items.to_staff_table(staff_table);
    }//GEN-LAST:event_reset_btnActionPerformed

    private void staff_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staff_tableMouseClicked
        get_id(staff_table);
    }//GEN-LAST:event_staff_tableMouseClicked

    private static int item_stock;
    private static int newStock = 0;
    private static int get_item_id;

    private void get_id(JTable table) {
        int rowIndex = table.getSelectedRow();
        if (rowIndex < 0) {
            Notifications.getInstance().show(Notifications.Type.ERROR, "Please select and item first!");
        } else {
            TableModel model = table.getModel();

            try {
                databaseConnector dbc = new databaseConnector();
                ResultSet rs = dbc.getData("SELECT * FROM tbl_items WHERE item_SKU =" + model.getValueAt(rowIndex, 0));

                if (rs.next()) {
                    get_item_id = rs.getInt("item_SKU");
                    item_stock = rs.getInt("item_stocks");
                    quan = rs.getInt("item_stocks");
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error retrieving data: " + e.getMessage());
                System.out.println(e.getMessage());
            }
        }
    }

    private void updateProductSold(int quantitySold, int productId) {
        databaseConnector dbc = new databaseConnector();
        String sql;
        sql = "UPDATE tbl_items SET total_sold = total_sold + ? WHERE item_SKU = ?";
        try (PreparedStatement pst = dbc.getConnection().prepareStatement(sql)) {
            pst.setInt(1, quantitySold);
            pst.setInt(2, productId);
            pst.executeUpdate();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "SQL Error updating product sold data: " + e.getMessage());
        }
    }

    public static void updateStock(int newStock, int productId) {
        try {

            databaseConnector dbc = new databaseConnector();

            String updateQuery = "UPDATE tbl_items SET item_stocks = ? WHERE item_SKU = ?";
            PreparedStatement pst = dbc.getConnection().prepareStatement(updateQuery);
            pst.setInt(1, newStock);
            pst.setInt(2, productId);
            pst.executeUpdate();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error executing SQL query: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println("SQLException: " + e.getMessage());
        }
    }

    public static void updateStatus(String status) {
        try {
            databaseConnector dbc = new databaseConnector();

            String updateQuery = "UPDATE tbl_items SET item_status = ? WHERE item_SKU = ?";
            PreparedStatement pst = dbc.getConnection().prepareStatement(updateQuery);
            pst.setString(1, status);
            pst.setInt(2, get_item_id);
            pst.executeUpdate();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error executing SQL query: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println("SQLException: " + e.getMessage());
        }
    }

    private void buy_now_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buy_now_btnActionPerformed
        int rowIndex = staff_table.getSelectedRow();
        newStock = item_stock - num;
        if (rowIndex < 0) {
            Notifications.getInstance().show(Notifications.Type.ERROR, "Please select and item first!");
            return;
        }
        databaseConnector dbc = new databaseConnector();
        updateStock(newStock, get_item_id);
        if (newStock < 1) {
            updateStatus("soldout");
        }
        updateProductSold(num, get_item_id);
        Notifications.getInstance().show(Notifications.Type.SUCCESS, "Item has been accepted successfully!");

        String action = "Buy";
        String details = "User " + user_id + " sold item " + get_item_id + "successfully!";
        actionLogs.recordAdminLogs(user_id, action, details);
        newStock = 0;
        display_items.to_staff_table(staff_table);
    }//GEN-LAST:event_buy_now_btnActionPerformed

    private void materialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialActionPerformed
        sorter.searchResult(staff_table, material);
    }//GEN-LAST:event_materialActionPerformed

    private int num = 1;
    int quan = 1;

    private void decrementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decrementActionPerformed
        if (num > 1) {
            num--;
            display_quantity.setText(String.valueOf(num));
        }
    }//GEN-LAST:event_decrementActionPerformed

    private void display_quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_display_quantityActionPerformed

    }//GEN-LAST:event_display_quantityActionPerformed

    private void incrementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incrementActionPerformed
        if (num < quan) {
            num++;
            display_quantity.setText(String.valueOf(num));
        } else {
            JOptionPane.showMessageDialog(null, "Insufficient stock. Available stock: " + quan);
        }
    }//GEN-LAST:event_incrementActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
            java.awt.EventQueue.invokeLater(() -> {
                new staff_dashboard().setVisible(true);
            });

        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(staff_dashboard.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel archived;
    private javax.swing.JButton buy_now_btn;
    private javax.swing.JButton call_admin_btn;
    private javax.swing.JComboBox<String> category;
    private javax.swing.JComboBox<String> color_option;
    private javax.swing.JPanel confimation;
    private javax.swing.JPanel dashboard;
    private javax.swing.JToggleButton dashboard_btn;
    private javax.swing.JLabel date_today;
    private javax.swing.JButton decrement;
    private javax.swing.JLabel discontinued;
    private javax.swing.JTextField display_quantity;
    private javax.swing.JPanel filterContainer2;
    private javax.swing.JPanel filterContainer3;
    private javax.swing.JPanel filterContainer4;
    private javax.swing.JPanel filterContainer5;
    private javax.swing.JPanel filterContainer6;
    private javax.swing.JButton find_btn_manage;
    private javax.swing.JButton increment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JToggleButton logout_btn;
    private javax.swing.JPanel manage_table_container;
    private javax.swing.JComboBox<String> material;
    private javax.swing.JToggleButton new_btn;
    private javax.swing.JToggleButton prelove_btn;
    private javax.swing.JLabel profile_icon1;
    private javax.swing.JButton reset_btn;
    private javax.swing.JTextField search_btn_manage;
    private javax.swing.JComboBox<String> size_option;
    private javax.swing.JTable staff_table;
    private javax.swing.JComboBox<String> supplier;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JPanel top_navbar;
    private javax.swing.JLabel total_items;
    // End of variables declaration//GEN-END:variables
}
