/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import com.formdev.flatlaf.FlatLightLaf;
import config.flatlaftTable;
import config.search;
import config.sorter;
import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import raven.toast.Notifications;

/**
 *
 * @author rico
 */
public class logs_dashboard extends javax.swing.JFrame {

    /**
     * Creates new form logs_dashboard
     */
    public logs_dashboard() {
        initComponents();
        display_items.logs(logs_table);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        logs_table = new javax.swing.JTable();
        print_btn = new javax.swing.JButton();
        search_btn_logs = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        filterContainer1 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logs_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(logs_table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 900, 430));

        print_btn.setText("Print");
        print_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_btnActionPerformed(evt);
            }
        });
        jPanel1.add(print_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, -1, 40));
        UXmethods.RoundBorders.setArcStyle(print_btn, 30);

        search_btn_logs.setSelectionColor(new java.awt.Color(255, 229, 246));
        search_btn_logs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_btn_logsKeyReleased(evt);
            }
        });
        jPanel1.add(search_btn_logs, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 200, 40));
        flatlaftTable.searchBar(search_btn_logs);
        UXmethods.RoundBorders.setArcStyle(search_btn_logs, 30);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel1.setText("Activity logs");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        filterContainer1.setBackground(new java.awt.Color(255, 255, 255));
        filterContainer1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setBackground(new java.awt.Color(241, 241, 241));
        jLabel34.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(51, 51, 51));
        jLabel34.setText("Filter by:");
        filterContainer1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 40));

        jComboBox4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jComboBox4.setForeground(new java.awt.Color(153, 153, 153));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "add item", "Restored", "edit item", "Logged in", "Logged out", " " }));
        jComboBox4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        filterContainer1.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 6, 110, 30));

        jPanel1.add(filterContainer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 180, 40));
        UXmethods.RoundBorders.setArcStyle(filterContainer1, 30);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void search_btn_logsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_btn_logsKeyReleased
        search.searchResult(logs_table, search_btn_logs);
    }//GEN-LAST:event_search_btn_logsKeyReleased

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        sorter.searchResult(logs_table, jComboBox4);
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void print_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_btnActionPerformed
        try {
            boolean complete = logs_table.print();
            if (complete) {
                // Show a success message
                Notifications.getInstance().show(Notifications.Type.SUCCESS, "Print Pomplete");
            } else {
                // Printing was canceled
                Notifications.getInstance().show(Notifications.Type.ERROR, "Printing Cancelled");

            }
        } catch (PrinterException pe) {
            // Handle the printing error
            Notifications.getInstance().show(Notifications.Type.WARNING, "Printing Failed!");
        }
    }//GEN-LAST:event_print_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
            java.awt.EventQueue.invokeLater(() -> {
                new logs_dashboard().setVisible(true);
            });
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(logs_dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel filterContainer1;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable logs_table;
    private javax.swing.JButton print_btn;
    private javax.swing.JTextField search_btn_logs;
    // End of variables declaration//GEN-END:variables
}
